package model.BusinessComponents.ViewObjects;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 23 19:34:24 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BranchUserAccounts_VODefImpl extends ViewDefImpl {
    public BranchUserAccounts_VODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public BranchUserAccounts_VODefImpl() {
    }
}

