package model.BusinessComponents.ViewObjects;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 24 22:44:48 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeUserAccounts_VODefImpl extends ViewDefImpl {
    public EmployeeUserAccounts_VODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeUserAccounts_VODefImpl() {
    }
}

