package model.BusinessComponents.ApplicationModules;

import model.BusinessComponents.ViewObjects.BranchUserAccounts_VOImpl;

import model.BusinessComponents.ViewObjects.EmployeeUserAccounts_VOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 23 18:57:59 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Express_AMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Express_AMImpl() {
    }

    /**
     * Container's getter for AwbAddresses1.
     * @return AwbAddresses1
     */
    public ViewObjectImpl getAwbAddresses1() {
        return (ViewObjectImpl) findViewObject("AwbAddresses1");
    }

    /**
     * Container's getter for Awb1.
     * @return Awb1
     */
    public ViewObjectImpl getAwb1() {
        return (ViewObjectImpl) findViewObject("Awb1");
    }

    /**
     * Container's getter for BranchUserAccounts1.
     * @return BranchUserAccounts1
     */
    public BranchUserAccounts_VOImpl getBranchUserAccounts1() {
        return (BranchUserAccounts_VOImpl) findViewObject("BranchUserAccounts1");
    }

    /**
     * Container's getter for Companies1.
     * @return Companies1
     */
    public ViewObjectImpl getCompanies1() {
        return (ViewObjectImpl) findViewObject("Companies1");
    }

    /**
     * Container's getter for CompanyBranches1.
     * @return CompanyBranches1
     */
    public ViewObjectImpl getCompanyBranches1() {
        return (ViewObjectImpl) findViewObject("CompanyBranches1");
    }

    /**
     * Container's getter for ContractTerms1.
     * @return ContractTerms1
     */
    public ViewObjectImpl getContractTerms1() {
        return (ViewObjectImpl) findViewObject("ContractTerms1");
    }

    /**
     * Container's getter for Contracts1.
     * @return Contracts1
     */
    public ViewObjectImpl getContracts1() {
        return (ViewObjectImpl) findViewObject("Contracts1");
    }

    /**
     * Container's getter for Delevered1.
     * @return Delevered1
     */
    public ViewObjectImpl getDelevered1() {
        return (ViewObjectImpl) findViewObject("Delevered1");
    }

    /**
     * Container's getter for Departments1.
     * @return Departments1
     */
    public ViewObjectImpl getDepartments1() {
        return (ViewObjectImpl) findViewObject("Departments1");
    }

    /**
     * Container's getter for EmployeeUserAccounts1.
     * @return EmployeeUserAccounts1
     */
    public EmployeeUserAccounts_VOImpl getEmployeeUserAccounts1() {
        return (EmployeeUserAccounts_VOImpl) findViewObject("EmployeeUserAccounts1");
    }

    /**
     * Container's getter for Employees1.
     * @return Employees1
     */
    public ViewObjectImpl getEmployees1() {
        return (ViewObjectImpl) findViewObject("Employees1");
    }

    /**
     * Container's getter for Items1.
     * @return Items1
     */
    public ViewObjectImpl getItems1() {
        return (ViewObjectImpl) findViewObject("Items1");
    }

    /**
     * Container's getter for Modules1.
     * @return Modules1
     */
    public ViewObjectImpl getModules1() {
        return (ViewObjectImpl) findViewObject("Modules1");
    }

    /**
     * Container's getter for OnDelevery1.
     * @return OnDelevery1
     */
    public ViewObjectImpl getOnDelevery1() {
        return (ViewObjectImpl) findViewObject("OnDelevery1");
    }

    /**
     * Container's getter for Orders1.
     * @return Orders1
     */
    public ViewObjectImpl getOrders1() {
        return (ViewObjectImpl) findViewObject("Orders1");
    }

    /**
     * Container's getter for Pages1.
     * @return Pages1
     */
    public ViewObjectImpl getPages1() {
        return (ViewObjectImpl) findViewObject("Pages1");
    }

    /**
     * Container's getter for PickUp1.
     * @return PickUp1
     */
    public ViewObjectImpl getPickUp1() {
        return (ViewObjectImpl) findViewObject("PickUp1");
    }

    /**
     * Container's getter for Representatives1.
     * @return Representatives1
     */
    public ViewObjectImpl getRepresentatives1() {
        return (ViewObjectImpl) findViewObject("Representatives1");
    }

    /**
     * Container's getter for Returned1.
     * @return Returned1
     */
    public ViewObjectImpl getReturned1() {
        return (ViewObjectImpl) findViewObject("Returned1");
    }

    /**
     * Container's getter for RolePages1.
     * @return RolePages1
     */
    public ViewObjectImpl getRolePages1() {
        return (ViewObjectImpl) findViewObject("RolePages1");
    }

    /**
     * Container's getter for Roles1.
     * @return Roles1
     */
    public ViewObjectImpl getRoles1() {
        return (ViewObjectImpl) findViewObject("Roles1");
    }

    /**
     * Container's getter for Safe1.
     * @return Safe1
     */
    public ViewObjectImpl getSafe1() {
        return (ViewObjectImpl) findViewObject("Safe1");
    }

    /**
     * Container's getter for TrackingHistory1.
     * @return TrackingHistory1
     */
    public ViewObjectImpl getTrackingHistory1() {
        return (ViewObjectImpl) findViewObject("TrackingHistory1");
    }

    /**
     * Container's getter for ZonesPaymentPlans1.
     * @return ZonesPaymentPlans1
     */
    public ViewObjectImpl getZonesPaymentPlans1() {
        return (ViewObjectImpl) findViewObject("ZonesPaymentPlans1");
    }

    /**
     * Container's getter for Zones1.
     * @return Zones1
     */
    public ViewObjectImpl getZones1() {
        return (ViewObjectImpl) findViewObject("Zones1");
    }

    /**
     * Container's getter for AwbAddresses2.
     * @return AwbAddresses2
     */
    public ViewObjectImpl getAwbAddresses2() {
        return (ViewObjectImpl) findViewObject("AwbAddresses2");
    }

    /**
     * Container's getter for Awb2.
     * @return Awb2
     */
    public ViewObjectImpl getAwb2() {
        return (ViewObjectImpl) findViewObject("Awb2");
    }

    /**
     * Container's getter for AwbAddresses3.
     * @return AwbAddresses3
     */
    public ViewObjectImpl getAwbAddresses3() {
        return (ViewObjectImpl) findViewObject("AwbAddresses3");
    }

    /**
     * Container's getter for CompanyBranches2.
     * @return CompanyBranches2
     */
    public ViewObjectImpl getCompanyBranches2() {
        return (ViewObjectImpl) findViewObject("CompanyBranches2");
    }

    /**
     * Container's getter for CompanyBranches3.
     * @return CompanyBranches3
     */
    public ViewObjectImpl getCompanyBranches3() {
        return (ViewObjectImpl) findViewObject("CompanyBranches3");
    }

    /**
     * Container's getter for Contracts2.
     * @return Contracts2
     */
    public ViewObjectImpl getContracts2() {
        return (ViewObjectImpl) findViewObject("Contracts2");
    }

    /**
     * Container's getter for ContractTerms2.
     * @return ContractTerms2
     */
    public ViewObjectImpl getContractTerms2() {
        return (ViewObjectImpl) findViewObject("ContractTerms2");
    }

    /**
     * Container's getter for Delevered2.
     * @return Delevered2
     */
    public ViewObjectImpl getDelevered2() {
        return (ViewObjectImpl) findViewObject("Delevered2");
    }

    /**
     * Container's getter for Delevered3.
     * @return Delevered3
     */
    public ViewObjectImpl getDelevered3() {
        return (ViewObjectImpl) findViewObject("Delevered3");
    }

    /**
     * Container's getter for Contracts3.
     * @return Contracts3
     */
    public ViewObjectImpl getContracts3() {
        return (ViewObjectImpl) findViewObject("Contracts3");
    }

    /**
     * Container's getter for Employees2.
     * @return Employees2
     */
    public ViewObjectImpl getEmployees2() {
        return (ViewObjectImpl) findViewObject("Employees2");
    }

    /**
     * Container's getter for Employees3.
     * @return Employees3
     */
    public ViewObjectImpl getEmployees3() {
        return (ViewObjectImpl) findViewObject("Employees3");
    }

    /**
     * Container's getter for Items2.
     * @return Items2
     */
    public ViewObjectImpl getItems2() {
        return (ViewObjectImpl) findViewObject("Items2");
    }

    /**
     * Container's getter for OnDelevery2.
     * @return OnDelevery2
     */
    public ViewObjectImpl getOnDelevery2() {
        return (ViewObjectImpl) findViewObject("OnDelevery2");
    }

    /**
     * Container's getter for OnDelevery3.
     * @return OnDelevery3
     */
    public ViewObjectImpl getOnDelevery3() {
        return (ViewObjectImpl) findViewObject("OnDelevery3");
    }

    /**
     * Container's getter for Awb3.
     * @return Awb3
     */
    public ViewObjectImpl getAwb3() {
        return (ViewObjectImpl) findViewObject("Awb3");
    }

    /**
     * Container's getter for Orders2.
     * @return Orders2
     */
    public ViewObjectImpl getOrders2() {
        return (ViewObjectImpl) findViewObject("Orders2");
    }

    /**
     * Container's getter for Orders3.
     * @return Orders3
     */
    public ViewObjectImpl getOrders3() {
        return (ViewObjectImpl) findViewObject("Orders3");
    }

    /**
     * Container's getter for Orders4.
     * @return Orders4
     */
    public ViewObjectImpl getOrders4() {
        return (ViewObjectImpl) findViewObject("Orders4");
    }

    /**
     * Container's getter for Pages2.
     * @return Pages2
     */
    public ViewObjectImpl getPages2() {
        return (ViewObjectImpl) findViewObject("Pages2");
    }

    /**
     * Container's getter for PickUp2.
     * @return PickUp2
     */
    public ViewObjectImpl getPickUp2() {
        return (ViewObjectImpl) findViewObject("PickUp2");
    }

    /**
     * Container's getter for PickUp3.
     * @return PickUp3
     */
    public ViewObjectImpl getPickUp3() {
        return (ViewObjectImpl) findViewObject("PickUp3");
    }

    /**
     * Container's getter for Contracts4.
     * @return Contracts4
     */
    public ViewObjectImpl getContracts4() {
        return (ViewObjectImpl) findViewObject("Contracts4");
    }

    /**
     * Container's getter for Representatives2.
     * @return Representatives2
     */
    public ViewObjectImpl getRepresentatives2() {
        return (ViewObjectImpl) findViewObject("Representatives2");
    }

    /**
     * Container's getter for Representatives3.
     * @return Representatives3
     */
    public ViewObjectImpl getRepresentatives3() {
        return (ViewObjectImpl) findViewObject("Representatives3");
    }

    /**
     * Container's getter for Returned2.
     * @return Returned2
     */
    public ViewObjectImpl getReturned2() {
        return (ViewObjectImpl) findViewObject("Returned2");
    }

    /**
     * Container's getter for Returned3.
     * @return Returned3
     */
    public ViewObjectImpl getReturned3() {
        return (ViewObjectImpl) findViewObject("Returned3");
    }

    /**
     * Container's getter for BranchUserAccounts2.
     * @return BranchUserAccounts2
     */
    public BranchUserAccounts_VOImpl getBranchUserAccounts2() {
        return (BranchUserAccounts_VOImpl) findViewObject("BranchUserAccounts2");
    }

    /**
     * Container's getter for EmployeeUserAccounts2.
     * @return EmployeeUserAccounts2
     */
    public EmployeeUserAccounts_VOImpl getEmployeeUserAccounts2() {
        return (EmployeeUserAccounts_VOImpl) findViewObject("EmployeeUserAccounts2");
    }

    /**
     * Container's getter for RolePages2.
     * @return RolePages2
     */
    public ViewObjectImpl getRolePages2() {
        return (ViewObjectImpl) findViewObject("RolePages2");
    }

    /**
     * Container's getter for RolePages3.
     * @return RolePages3
     */
    public ViewObjectImpl getRolePages3() {
        return (ViewObjectImpl) findViewObject("RolePages3");
    }

    /**
     * Container's getter for TrackingHistory2.
     * @return TrackingHistory2
     */
    public ViewObjectImpl getTrackingHistory2() {
        return (ViewObjectImpl) findViewObject("TrackingHistory2");
    }

    /**
     * Container's getter for CompanyBranches4.
     * @return CompanyBranches4
     */
    public ViewObjectImpl getCompanyBranches4() {
        return (ViewObjectImpl) findViewObject("CompanyBranches4");
    }

    /**
     * Container's getter for AwbAddresses4.
     * @return AwbAddresses4
     */
    public ViewObjectImpl getAwbAddresses4() {
        return (ViewObjectImpl) findViewObject("AwbAddresses4");
    }

    /**
     * Container's getter for ZonesPaymentPlans2.
     * @return ZonesPaymentPlans2
     */
    public ViewObjectImpl getZonesPaymentPlans2() {
        return (ViewObjectImpl) findViewObject("ZonesPaymentPlans2");
    }

    /**
     * Container's getter for ZonesPaymentPlans3.
     * @return ZonesPaymentPlans3
     */
    public ViewObjectImpl getZonesPaymentPlans3() {
        return (ViewObjectImpl) findViewObject("ZonesPaymentPlans3");
    }

    /**
     * Container's getter for ZonesPaymentPlans4.
     * @return ZonesPaymentPlans4
     */
    public ViewObjectImpl getZonesPaymentPlans4() {
        return (ViewObjectImpl) findViewObject("ZonesPaymentPlans4");
    }

    /**
     * Container's getter for AwbAddressesAwbFk1_VL1.
     * @return AwbAddressesAwbFk1_VL1
     */
    public ViewLinkImpl getAwbAddressesAwbFk1_VL1() {
        return (ViewLinkImpl) findViewLink("AwbAddressesAwbFk1_VL1");
    }

    /**
     * Container's getter for AwbBranchsourceFk1_VL1.
     * @return AwbBranchsourceFk1_VL1
     */
    public ViewLinkImpl getAwbBranchsourceFk1_VL1() {
        return (ViewLinkImpl) findViewLink("AwbBranchsourceFk1_VL1");
    }

    /**
     * Container's getter for AwbAddressesBranchesFk1_VL1.
     * @return AwbAddressesBranchesFk1_VL1
     */
    public ViewLinkImpl getAwbAddressesBranchesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("AwbAddressesBranchesFk1_VL1");
    }

    /**
     * Container's getter for CompanyBranchesAccountsFk2_VL1.
     * @return CompanyBranchesAccountsFk2_VL1
     */
    public ViewLinkImpl getCompanyBranchesAccountsFk2_VL1() {
        return (ViewLinkImpl) findViewLink("CompanyBranchesAccountsFk2_VL1");
    }

    /**
     * Container's getter for CompanyBranchesFk1_VL1.
     * @return CompanyBranchesFk1_VL1
     */
    public ViewLinkImpl getCompanyBranchesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("CompanyBranchesFk1_VL1");
    }

    /**
     * Container's getter for ContracsCompanyFk1_VL1.
     * @return ContracsCompanyFk1_VL1
     */
    public ViewLinkImpl getContracsCompanyFk1_VL1() {
        return (ViewLinkImpl) findViewLink("ContracsCompanyFk1_VL1");
    }

    /**
     * Container's getter for ContractTermsFk1_VL1.
     * @return ContractTermsFk1_VL1
     */
    public ViewLinkImpl getContractTermsFk1_VL1() {
        return (ViewLinkImpl) findViewLink("ContractTermsFk1_VL1");
    }

    /**
     * Container's getter for DeleveredAwbFk1_VL1.
     * @return DeleveredAwbFk1_VL1
     */
    public ViewLinkImpl getDeleveredAwbFk1_VL1() {
        return (ViewLinkImpl) findViewLink("DeleveredAwbFk1_VL1");
    }

    /**
     * Container's getter for DeleveredEmployeesFk1_VL1.
     * @return DeleveredEmployeesFk1_VL1
     */
    public ViewLinkImpl getDeleveredEmployeesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("DeleveredEmployeesFk1_VL1");
    }

    /**
     * Container's getter for ContracsEmpFk1_VL1.
     * @return ContracsEmpFk1_VL1
     */
    public ViewLinkImpl getContracsEmpFk1_VL1() {
        return (ViewLinkImpl) findViewLink("ContracsEmpFk1_VL1");
    }

    /**
     * Container's getter for EmployeesFk1_VL1.
     * @return EmployeesFk1_VL1
     */
    public ViewLinkImpl getEmployeesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("EmployeesFk1_VL1");
    }

    /**
     * Container's getter for EmployeesAccountsFk2_VL1.
     * @return EmployeesAccountsFk2_VL1
     */
    public ViewLinkImpl getEmployeesAccountsFk2_VL1() {
        return (ViewLinkImpl) findViewLink("EmployeesAccountsFk2_VL1");
    }

    /**
     * Container's getter for ItemsAwbFk1_VL1.
     * @return ItemsAwbFk1_VL1
     */
    public ViewLinkImpl getItemsAwbFk1_VL1() {
        return (ViewLinkImpl) findViewLink("ItemsAwbFk1_VL1");
    }

    /**
     * Container's getter for OnDeleveryAwbFk1_VL1.
     * @return OnDeleveryAwbFk1_VL1
     */
    public ViewLinkImpl getOnDeleveryAwbFk1_VL1() {
        return (ViewLinkImpl) findViewLink("OnDeleveryAwbFk1_VL1");
    }

    /**
     * Container's getter for OnDeleveryEmployeesFk1_VL1.
     * @return OnDeleveryEmployeesFk1_VL1
     */
    public ViewLinkImpl getOnDeleveryEmployeesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("OnDeleveryEmployeesFk1_VL1");
    }

    /**
     * Container's getter for AwbOrdersFk1_VL1.
     * @return AwbOrdersFk1_VL1
     */
    public ViewLinkImpl getAwbOrdersFk1_VL1() {
        return (ViewLinkImpl) findViewLink("AwbOrdersFk1_VL1");
    }

    /**
     * Container's getter for OrdersBranchFk1_VL1.
     * @return OrdersBranchFk1_VL1
     */
    public ViewLinkImpl getOrdersBranchFk1_VL1() {
        return (ViewLinkImpl) findViewLink("OrdersBranchFk1_VL1");
    }

    /**
     * Container's getter for OrdersCompanyFk1_VL1.
     * @return OrdersCompanyFk1_VL1
     */
    public ViewLinkImpl getOrdersCompanyFk1_VL1() {
        return (ViewLinkImpl) findViewLink("OrdersCompanyFk1_VL1");
    }

    /**
     * Container's getter for OrdersContractFk1_VL1.
     * @return OrdersContractFk1_VL1
     */
    public ViewLinkImpl getOrdersContractFk1_VL1() {
        return (ViewLinkImpl) findViewLink("OrdersContractFk1_VL1");
    }

    /**
     * Container's getter for PagesModulesFk1_VL1.
     * @return PagesModulesFk1_VL1
     */
    public ViewLinkImpl getPagesModulesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("PagesModulesFk1_VL1");
    }

    /**
     * Container's getter for PickUpAwbFk1_VL1.
     * @return PickUpAwbFk1_VL1
     */
    public ViewLinkImpl getPickUpAwbFk1_VL1() {
        return (ViewLinkImpl) findViewLink("PickUpAwbFk1_VL1");
    }

    /**
     * Container's getter for PickUpEmployeesFk1_VL1.
     * @return PickUpEmployeesFk1_VL1
     */
    public ViewLinkImpl getPickUpEmployeesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("PickUpEmployeesFk1_VL1");
    }

    /**
     * Container's getter for ContracsRepFk1_VL1.
     * @return ContracsRepFk1_VL1
     */
    public ViewLinkImpl getContracsRepFk1_VL1() {
        return (ViewLinkImpl) findViewLink("ContracsRepFk1_VL1");
    }

    /**
     * Container's getter for RepresentativesFk1_VL1.
     * @return RepresentativesFk1_VL1
     */
    public ViewLinkImpl getRepresentativesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("RepresentativesFk1_VL1");
    }

    /**
     * Container's getter for RepresentativesFk2_VL1.
     * @return RepresentativesFk2_VL1
     */
    public ViewLinkImpl getRepresentativesFk2_VL1() {
        return (ViewLinkImpl) findViewLink("RepresentativesFk2_VL1");
    }

    /**
     * Container's getter for ReturnedAwbFk1_VL1.
     * @return ReturnedAwbFk1_VL1
     */
    public ViewLinkImpl getReturnedAwbFk1_VL1() {
        return (ViewLinkImpl) findViewLink("ReturnedAwbFk1_VL1");
    }

    /**
     * Container's getter for ReturnedEmployeesFk1_VL1.
     * @return ReturnedEmployeesFk1_VL1
     */
    public ViewLinkImpl getReturnedEmployeesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("ReturnedEmployeesFk1_VL1");
    }

    /**
     * Container's getter for BranchAccountsRolesFk1_VL1.
     * @return BranchAccountsRolesFk1_VL1
     */
    public ViewLinkImpl getBranchAccountsRolesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("BranchAccountsRolesFk1_VL1");
    }

    /**
     * Container's getter for EmployeeAccountsRolesFk1_VL1.
     * @return EmployeeAccountsRolesFk1_VL1
     */
    public ViewLinkImpl getEmployeeAccountsRolesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("EmployeeAccountsRolesFk1_VL1");
    }

    /**
     * Container's getter for RolePagesPagesFk1_VL1.
     * @return RolePagesPagesFk1_VL1
     */
    public ViewLinkImpl getRolePagesPagesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("RolePagesPagesFk1_VL1");
    }

    /**
     * Container's getter for RolePagesRolesFk1_VL1.
     * @return RolePagesRolesFk1_VL1
     */
    public ViewLinkImpl getRolePagesRolesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("RolePagesRolesFk1_VL1");
    }

    /**
     * Container's getter for TrackingHistoryFk1_VL1.
     * @return TrackingHistoryFk1_VL1
     */
    public ViewLinkImpl getTrackingHistoryFk1_VL1() {
        return (ViewLinkImpl) findViewLink("TrackingHistoryFk1_VL1");
    }

    /**
     * Container's getter for CompanyBranchesZonesFk2_VL1.
     * @return CompanyBranchesZonesFk2_VL1
     */
    public ViewLinkImpl getCompanyBranchesZonesFk2_VL1() {
        return (ViewLinkImpl) findViewLink("CompanyBranchesZonesFk2_VL1");
    }

    /**
     * Container's getter for AwbAddressesZonesFk1_VL1.
     * @return AwbAddressesZonesFk1_VL1
     */
    public ViewLinkImpl getAwbAddressesZonesFk1_VL1() {
        return (ViewLinkImpl) findViewLink("AwbAddressesZonesFk1_VL1");
    }

    /**
     * Container's getter for PaymentPlansDzoneFk1_VL1.
     * @return PaymentPlansDzoneFk1_VL1
     */
    public ViewLinkImpl getPaymentPlansDzoneFk1_VL1() {
        return (ViewLinkImpl) findViewLink("PaymentPlansDzoneFk1_VL1");
    }

    /**
     * Container's getter for PaymentPlansSzoneFk1_VL1.
     * @return PaymentPlansSzoneFk1_VL1
     */
    public ViewLinkImpl getPaymentPlansSzoneFk1_VL1() {
        return (ViewLinkImpl) findViewLink("PaymentPlansSzoneFk1_VL1");
    }

    /**
     * Container's getter for ZonesPaymentPlansFk1_VL1.
     * @return ZonesPaymentPlansFk1_VL1
     */
    public ViewLinkImpl getZonesPaymentPlansFk1_VL1() {
        return (ViewLinkImpl) findViewLink("ZonesPaymentPlansFk1_VL1");
    }
    
    public void setWhererClouse(String viewObjectName,String name){
        findViewObject(viewObjectName).setWhereClause("");
    }

}

